version: 2
jobs:
  build:
    branches:
      only:
        - circleci
    docker:
      - image: circleci/python:3.6.5
    steps:
      - checkout
      - run: make package_test
      - run: make test
      - run: make clean