# following example here: https://dev.to/jonatasbaldin/a-recipe-for-poetry-and-circleci-1bj6
version: 2
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.7.4
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
      # Let's install the dependencies
      - run:
          name: Install Dependencies
          command: |
            poetry install
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
      # Another step, run flake8
      - run:
          name: Run linter
          command: |
            make lint
      # Last step, runs our tests omitting the dependencies path (so we don't take their coverage into account)
      # And send our coverage somewhere, in this case, coveralls
      - run:
          name: Run unittest
          command: |
            make test

workflows:
  version: 2
  build-and-test-workflow:
    jobs:
      - build-and-test


